name: StackSprint CI/CD Pipeline

# TEACHING NOTE: CI/CD PIPELINES
# This workflow runs automatically every time code is pushed to the 'develop', 'master' or 'main' branch.
# It ensures that no broken code is ever merged into the project.
# We test Java, Node.js, and Python concurrently to save time!

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test-say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello JQAMA
      run: echo "Hello, JQAMA!!"
  test-task-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Node.js Code
      uses: actions/checkout@v3

    - name: Setup Node.js 24
      uses: actions/setup-node@v3
      with:
        node-version: 24
    
    - name: Install Dependencies and Run Tests
      working-directory: ./services/task-service
      run: |
        npm install
        npm run test
      
  test-analytics-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Python Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies & Run Pytest
      working-directory: ./services/analytics-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest

  test-user-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Java code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Make Maven Wrapper executable
      working-directory: ./services/user-service
      run: chmod +x mvnw        

    - name: Run JUnit Tests
      working-directory: ./services/user-service
      run: ./mvnw test

  test-web-client-e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Next.js code
      uses: actions/checkout@v3

    - name: Set up Node.js 24
      uses: actions/setup-node@v3
      with:
        node-version: '24'
        
    - name: Install dependencies
      working-directory: ./apps/web-client
      run: npm install
      
    # Playwright requires the actual browser binaries to be downloaded
    - name: Install Playwright Browsers
      working-directory: ./apps/web-client
      run: npx playwright install --with-deps
      
    - name: Run Playwright E2E tests
      working-directory: ./apps/web-client
      run: npx playwright test